# Generated by Django 4.0.5 on 2023-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='categoria',
            field=models.CharField(choices=[('P', 'Particular'), ('T', 'Transporte'), ('C', 'Carga')], default='Particular', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculomodel',
            name='marca',
            field=models.CharField(choices=[(1, 'Ford'), (2, 'Fiat'), (3, 'Chevrolet'), (4, 'Toyota')], default='Ford', max_length=20),
        ),
    ]
