# Generated by Django 4.0.5 on 2023-07-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculomodel_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodel',
            name='marca',
            field=models.CharField(choices=[('1', 'Ford'), ('2', 'Fiat'), ('3', 'Chevrolet'), ('4', 'Toyota')], default='Ford', max_length=20),
        ),
    ]
