# Generated by Django 4.0.5 on 2023-07-07 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculomodel_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Libros'},
        ),
    ]
