# Generated by Django 4.0.5 on 2023-07-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculomodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodel',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Vehiculos'},
        ),
    ]
